version: '3'

services:
  docker-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=05ernest22
      - MYSQL_DATABASE=database
      - MYSQL_USER=submanager
      - MYSQL_PASSWORD=05ernest22
    ports:
      - 3307:3306

  app:
    image: airnest97/submanager:latest
    ports:
      - 9090:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/database?autoReconnect=true&useSSL=false
    depends_on:
      - docker-mysql
